# Generated by Django 4.2.3 on 2024-01-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Id de Productos')),
                ('nombreProducto', models.CharField(blank=True, max_length=25, verbose_name='Nombre')),
                ('precio', models.IntegerField(blank=True, verbose_name='Precio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=50, verbose_name='Descripcion')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
