# Generated by Django 4.2.3 on 2024-01-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.CharField(blank=True, max_length=7, verbose_name='Precio'),
        ),
    ]
