# Generated by Django 5.0.1 on 2024-01-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=25, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=25, verbose_name='Apellido')),
                ('correo', models.CharField(blank=True, max_length=50, verbose_name='Correo')),
                ('consulta', models.CharField(blank=True, max_length=100, verbose_name='Consulta')),
            ],
        ),
    ]
