# Generated by Django 5.0.1 on 2024-01-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
