# Generated by Django 5.0.1 on 2024-01-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_alter_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_boleta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito.usuario'),
        ),
    ]
