# Generated by Django 5.0.1 on 2024-01-30 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_detalle_boleta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.usuario'),
        ),
    ]
