# Generated by Django 5.0.1 on 2024-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_alter_detalle_boleta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_boleta',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Nombre'),
        ),
    ]
