# Generated by Django 5.0.1 on 2024-01-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_remove_detalle_boleta_usuario_alter_usuario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='id_Producto',
            new_name='idProducto',
        ),
    ]
