# Generated by Django 5.0.1 on 2024-01-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_rename_id_producto_detalle_boleta_idproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='idProducto',
            new_name='id_Producto',
        ),
    ]
